version: '3'
services:
  wild_palms_io:
    image: wild_palms_io
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./:/wild_palms_io
    depends_on:
      - db
    command: /bin/bash -c  'mix ecto.create && mix ecto.migrate && mix phx.server'
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
